namespace DeepBrain.Shared.BrainDtos.V6;

public sealed record MlPolicyDto(
    bool Enabled,
    int InputDim,
    int ActionCount,
    int BufferSize,
    int BufferCapacity,
    double Epsilon,
    double NetWeight,
    double LastLoss,
    double AvgLoss100,
    double AvgReward200,
    double AvgQ,
    double Entropy,
    long TrainSteps,
    int NanSkips,
    int IllegalChoiceCount,
    int OverrideCount,
    int InvalidActionFallbackCount,
    string PolicySource,
    bool CoreAvailable,
    string BackendKind,
    bool RemoteConnected,
    double RttMs,
    string? LastRemoteError,
    string? ReasonIfDisabled,
    string MlMode,
    bool TrainEnabled,
    int TrainingEpisodeCount,
    int EvalEpisodeCount
);
