<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeepBrain.Shared\DeepBrain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup Condition=" '$(ML_CORE_PATH)' != '' and Exists('$(ML_CORE_PATH)') ">
    <ProjectReference Include="$(ML_CORE_PATH)" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="brainconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(ML_CORE_PATH)' != '' and Exists('$(ML_CORE_PATH)') ">
    <DefineConstants>$(DefineConstants);ML_CORE</DefineConstants>
  </PropertyGroup>

</Project>
